/**:
    ros__parameters:
      video_device: "/dev/video2"
      framerate: 30.0
      # io_method: "mmap"
      frame_id: "camera"
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
      # av_device_format: "YUV422P"
      image_width: 2560
      image_height: 960
      